imports:
  - src/Behat/Resources/config/suites.yml

#default:
#  suites:
#    ui_managing_users:
#      contexts:
#        - App\Behat\Context\FeatureContext
#  extensions:
#    Behat\MinkExtension:
#      base_url:  http://codeforfood.local
#      default_session: selenium2
#      javascript_session: chrome
#      sessions:
#        selenium2:
#          selenium2: ~
#        chrome:
#          selenium2:
#            browser: chrome
#            capabilities:
#              browserName: chrome
#              browser: chrome
#              version: ""
#              marionette: null # https://github.com/Behat/MinkExtension/pull/311
#              chrome:
#                switches:
#                  - "start-fullscreen"
#                  - "start-maximized"
#                  - "no-sandbox"
#              extra_capabilities:
#                unexpectedAlertBehaviour: accept
default:
  formatters:
    pretty:
      verbose: true
      paths: false
      snippets: false

  extensions:
    Lakion\Behat\MinkDebugExtension:
      directory: etc/build
      clean_start: false
      screenshot: true

    Behat\MinkExtension:
      files_path: "%paths.base%/src/Sylius/Behat/Resources/fixtures/"
      base_url: "http://codeforfood.local/"
      default_session: symfony
      javascript_session: chrome
      sessions:
        symfony:
          symfony: ~
        chrome:
          selenium2:
            browser: chrome
            capabilities:
              browserName: chrome
              browser: chrome
              version: ""
              marionette: null # https://github.com/Behat/MinkExtension/pull/311
              chrome:
                switches:
                  - "start-fullscreen"
                  - "start-maximized"
                  - "no-sandbox"
              extra_capabilities:
                unexpectedAlertBehaviour: accept
        firefox:
          selenium2:
            browser: firefox
      show_auto: false

    FriendsOfBehat\SymfonyExtension: ~

    FriendsOfBehat\VariadicExtension: ~

  gherkin:
    filters:
      tags: "~@todo && ~@cli" # CLI is excluded as it registers an error handler that mutes fatal errors

